import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const AllMyNotes = () => {
  const { data: Allnotes, isLoading } = trpc?.mynotes?.allNotes.useQuery();

  if (isLoading) return <>Loading...</>;

  return (
    <>
      {Allnotes?.map((note, index) => {
        return (
          <div key={index} className="border border-gray-100 px-4 py-4">
            <div className="flex items-center justify-between">
              <h5 className="text-1xl font-bold">{note.title}</h5>
              <div>X</div>
            </div>
          </div>
        );
      })}
    </>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen flex-col py-10 sm:container">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight sm:text-center sm:text-3xl">
            My all Notes
          </h1>
          <div>
            <Link
              className="inline-block rounded-lg bg-indigo-600 px-4 py-1.5 text-base font-semibold leading-7 text-white shadow-sm ring-1 ring-indigo-600 hover:bg-indigo-700 hover:ring-indigo-700"
              href="/newnote"
            >
              Add a note
            </Link>
          </div>
        </div>
        <div className="mt-5">
          <AllMyNotes />
        </div>
      </main>
    </>
  );
};

export default Home;
