import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

interface FormData {
  title: String;
  description: String;
}

const Newnote: NextPage = () => {
  const [data, setData] = useState<FormData>({
    title: "",
    description: "",
  });

  const handelDescriptionChange = (event) => {
    setData({
      ...data,
      description: event.target.value,
    });
  };

  const handelTitleChange = (event) => {
    setData({
      ...data,
      title: event.target.value,
    });
  };
  // const addNewNote = trpc.mynotes.newNote.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen flex-col justify-center py-10 md:container">
        <h1 className="mb-6 text-center text-3xl font-bold tracking-tight text-gray-900">
          Add new notes
        </h1>
        <form
          onSubmit={(event) => {
            event.preventDefault();
            //do a mutation here
            // setData({
            //   title: "",
            //   description: "",
            // });
          }}
        >
          <input
            type="text"
            required
            value={data.title}
            placeholder="Your title"
            onChange={(event) => handelTitleChange(event)}
            className="border-1 mb-2 block w-full rounded-sm border-blue-800 bg-neutral-100 px-4 py-2 focus:outline-none"
          />
          <textarea
            type="text-area"
            required
            value={data.description}
            placeholder="Your description"
            onChange={(event) => handelDescriptionChange(event)}
            className="border-1 mb-2 block w-full rounded-sm border-blue-800 bg-neutral-100 px-4 py-2 focus:outline-none"
          />
          <button
            type="submit"
            className="block w-full rounded-lg bg-indigo-600 px-4 py-1.5 text-base font-semibold leading-7 text-white shadow-sm ring-1 ring-indigo-600 hover:bg-indigo-700 hover:ring-indigo-700"
          >
            Add a note
          </button>
        </form>
      </main>
    </>
  );
};

export default Newnote;
